# -*- coding: utf-8 -*-
"""assign_clusters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJ-zW-STvTFD2Qo7N_iQZQCSYnwAsLl9
"""

from utils.embedding_utils import get_embedding
from utils.helpers import compute_similarities
import numpy as np

def assign_to_cluster(relationship, cluster_embeddings, model, tokenizer, use_flair=False):
    embedding = get_embedding(relationship, model, tokenizer, use_flair)
    similarities = compute_similarities(embedding, cluster_embeddings, similarity_metric='mean')
    best_cluster = max(similarities, key=similarities.get)
    return relationship, best_cluster

def assign_to_topk_clusters(relationship, cluster_embeddings, model, tokenizer, top_k=5, similarity_metric='mean', use_flair=False):
    embedding = get_embedding(relationship, model, tokenizer, use_flair)
    similarities = compute_similarities(embedding, cluster_embeddings, similarity_metric)
    sorted_similarities = sorted(similarities.items(), key=lambda item: item[1], reverse=True)
    top_clusters = [cluster for cluster, _ in sorted_similarities[:top_k]]
    return relationship, top_clusters

def assign_to_topk_clusters_classifier(relationship, model, tokenizer, classifier, top_k=5):
    embedding = get_embedding(relationship, model, tokenizer).reshape(1, -1)
    probs = classifier.predict_proba(embedding)[0]
    top_indices = np.argsort(probs)[-top_k:][::-1]
    top_clusters = [classifier.classes_[idx] for idx in top_indices]
    return relationship, top_clusters

