# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAPow2XI__eyi8nOn0zLoNrmyG5yTfHA
"""

from datasets import load_dataset
import pandas as pd
from datasets import Dataset

def load_gpt4_data(clusters_path, new_rels_path):
    clusters_df = pd.read_excel(clusters_path)
    clusters_df.drop(index=0, axis=0, inplace=True)
    clusters_df.drop(columns=[51], inplace=True)
    clusters_df.reset_index(drop=True, inplace=True)

    new_rels_df = pd.read_excel(new_rels_path)
    new_rels_df.drop(index=0, axis=0, inplace=True)
    new_rels_df.reset_index(drop=True, inplace=True)

    return clusters_df, new_rels_df

def load_set2_ground_truth_data(filepath):

    ground_truth_df = pd.read_excel(filepath)
    ground_truth_df = ground_truth_df.iloc[0:861]
    # ground_truth_df = ground_truth_df.drop(columns=['Unnamed: 8', 'Unnamed: 9']).reset_index(drop=True)

    ground_truth_data = []
    current_summary = None

    for i, row in ground_truth_df.iterrows():
        if pd.notna(row['News_Summary']):
            current_summary = row['News_Summary']
        ground_truth_data.append({
            'news_summary': current_summary,
            'source': str(row['edge_source']).lower() if pd.notna(row['edge_source']) else None,
            'target': str(row['edge_target']).lower() if pd.notna(row['edge_target']) else None,
            'relationship': row['edge_relationship']
        })

    return pd.DataFrame(ground_truth_data)

def load_set2_predicted_data(filepath, file_type='excel'):

    if file_type == 'excel':
        predicted_df = pd.read_excel(filepath)
    elif file_type == 'csv':
        predicted_df = pd.read_csv(filepath, header=None)
        predicted_df = predicted_df.iloc[:, :8]
        print(predicted_df.columns)
        predicted_df.columns = [
            'News_Summary', 'Mistral_name', 'Mistral_class_of_Entity',
            'Mistral_Type_of_Entity', 'Mistral_properties', 'Mistral_source',
            'Mistral_target', 'Mistral_relationship'
        ]
    else:
        raise ValueError("Unsupported file type. Use 'excel' or 'csv'.")

    return process_set2_predicted_data(predicted_df)

def process_set2_predicted_data(predicted_df):

    predicted_data = []

    for i, row in predicted_df.iterrows():
        sources = eval(row['Mistral_source']) if isinstance(row['Mistral_source'], str) else None
        targets = eval(row['Mistral_target']) if isinstance(row['Mistral_target'], str) else None
        relationships = eval(row['Mistral_relationship']) if isinstance(row['Mistral_relationship'], str) else None

        if sources is None or targets is None or relationships is None:
            continue

        for src, tgt, rel in zip(sources, targets, relationships):
            predicted_data.append({
                'news_summary': row['News_Summary'],
                'source': src.lower() if isinstance(src, str) and pd.notna(src) else None,
                'target': tgt.lower() if isinstance(tgt, str) and pd.notna(tgt) else None,
                'relationship': rel
            })

    return pd.DataFrame(predicted_data)

def extract_set2_common_pairs_and_relationships(ground_truth_df, predicted_df):

    common_data = []

    for summary in ground_truth_df['news_summary'].unique():
        print(f"Processing summary: {summary}")

        gt_pairs = ground_truth_df[ground_truth_df['news_summary'] == summary][['source', 'target', 'relationship']]
        pred_pairs = predicted_df[predicted_df['news_summary'] == summary][['source', 'target', 'relationship']]

        common_pairs = pd.merge(gt_pairs, pred_pairs, on=['source', 'target'], suffixes=('_gt', '_pred'))

        for _, row in common_pairs.iterrows():
            common_data.append({
                'news_summary': summary,
                'source': row['source'],
                'target': row['target'],
                'relationship_gt': row['relationship_gt'],
                'relationship_pred': row['relationship_pred']
            })

    result_df = pd.DataFrame(common_data)
    print(f"Resulting DataFrame shape: {result_df.shape}")

    return result_df

def load_conll04_data():
    from datasets import load_dataset
    dataset = load_dataset("DFKI-SLT/conll04")
    return dataset['train'], dataset['validation'], dataset['test']

def extract_relations_conll04(dataset: Dataset):
    data = []
    for example in dataset:
        tokens = example['tokens']
        entities = example['entities']
        relations = example['relations']

        for relation in relations:
            head_entity = entities[relation['head']]
            tail_entity = entities[relation['tail']]

            subject_tokens = tokens[head_entity['start']:head_entity['end']]
            object_tokens = tokens[tail_entity['start']:tail_entity['end']]

            subject = " ".join(subject_tokens)
            object_ = " ".join(object_tokens)
            sentence = " ".join(tokens)
            relation_type = relation['type']

            data.append({
                "sentence": sentence,
                "subject": subject,
                "object": object_,
                "relation": relation_type
            })
    return data

def extract_relations_and_merge(dataset: Dataset, mistral_file: str, gpt4_file: str):
    # Extract relations from the dataset
    data = extract_relations_conll04(dataset)
    df = pd.DataFrame(data)

    # Read model output files
    mistral_output = pd.read_csv(mistral_file, header=None)
    gpt4_output = pd.read_csv(gpt4_file, header=None)

    # Assign column names
    mistral_output.columns = ['sentence', 'subject', 'relation', 'object']
    gpt4_output.columns = ['sentence', 'subject', 'relation', 'object']

    # Merge ground truth and model outputs
    merged_df_mistral = pd.merge(df, mistral_output, on=['sentence', 'subject', 'object'], suffixes=('_gt', '_pred'))
    merged_df_gpt4 = pd.merge(df, gpt4_output, on=['sentence', 'subject', 'object'], suffixes=('_gt', '_pred'))

    # Select and rename relevant columns
    final_df_mistral = merged_df_mistral[['sentence', 'subject', 'object', 'relation_gt', 'relation_pred']]
    final_df_mistral.columns = ['sentence', 'subject', 'object', 'ground_truth_relation', 'predicted_relation']

    final_df_gpt4 = merged_df_gpt4[['sentence', 'subject', 'object', 'relation_gt', 'relation_pred']]
    final_df_gpt4.columns = ['sentence', 'subject', 'object', 'ground_truth_relation', 'predicted_relation']

    return final_df_mistral, final_df_gpt4

