# -*- coding: utf-8 -*-
"""embedding_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5RIZAWHe_A5IERjNB6Up_R0BLmqVZs3
"""

import torch
from transformers import AutoTokenizer, AutoModel
from flair.data import Sentence

def get_embedding(text, model, tokenizer, use_flair=False):
    if use_flair:
        sentence = Sentence(text)
        model.embed(sentence)
        return sentence.get_embedding().cpu().numpy()
    else:
        inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
        with torch.no_grad():
            outputs = model(**inputs)
        return outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()

def get_cluster_embeddings(clusters_df, model, tokenizer):
    clusters = {col: clusters_df[col].dropna().tolist() for col in clusters_df.columns}
    cluster_embeddings = {cluster: [get_embedding(word, model, tokenizer, use_flair=False) for word in words] for cluster, words in clusters.items()}
    return clusters, cluster_embeddings

def get_embeddings_conll04(df_train, df_val, df_test, model, tokenizer):
    for df in [df_train, df_val, df_test]:
        df['predicted_relation'] = df['predicted_relation'].astype(str)

        def embed_relation(relation):
            try:
                return get_embedding(relation, model, tokenizer, use_flair=False).flatten()
            except Exception as e:
                print(f"Error embedding relation: {relation}, Error: {e}")
                return None
        df['predicted_relation_embedding'] = df['predicted_relation'].apply(embed_relation)
    return df_train, df_val, df_test