# -*- coding: utf-8 -*-
"""helpers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1O5FIHcT9STVJiV1vpkILF4Yx3_ysxb
"""

import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def load_model_and_tokenizer(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name)
    return tokenizer, model

def compute_similarities(embedding, cluster_embeddings, similarity_metric='mean'):
    similarities = {}
    for cluster, embeddings in cluster_embeddings.items():
        cluster_similarities = cosine_similarity([embedding], embeddings)
        if similarity_metric == 'mean':
            similarity_score = cluster_similarities.mean()
        elif similarity_metric == 'median':
            similarity_score = np.median(cluster_similarities)
        else:
            raise ValueError("Invalid similarity_metric. Choose 'mean' or 'median'.")
        similarities[cluster] = similarity_score
    return similarities

def save_data_to_excel(df, filename):
    df.to_excel(filename, index=False)









