# -*- coding: utf-8 -*-
"""model_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOMTd3tkn6pe1OteyZTyn3VOCzdrB9Gx
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder

def train_classifier(X_train, y_train):
    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(X_train, y_train)
    return clf

def evaluate_model(clf, X, y, label_encoder):
    y_pred = clf.predict(X)
    accuracy = accuracy_score(y, y_pred)
    f1_micro = f1_score(y, y_pred, average='micro')
    f1_macro = f1_score(y, y_pred, average='macro')
    class_report = classification_report(y, y_pred, target_names=label_encoder.classes_)
    return accuracy, f1_micro, f1_macro, class_report







