# -*- coding: utf-8 -*-
"""set2_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cPgZm6ehIHiByQRdPu6huCm4TGXry-V
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import sys
# import os
# sys.path.append('/content/drive/folder_location/Jio Internship Codes')

# !pip install datasets

import pandas as pd
from utils.data_processing import load_set2_ground_truth_data, load_set2_predicted_data, process_set2_predicted_data, extract_set2_common_pairs_and_relationships
from utils.helpers import save_data_to_excel

# Load ground truth data
ground_truth_df_processed = load_set2_ground_truth_data('../data/EntityRelationship_ManualLabel_Set2.xlsx')
# ground_truth_df_processed = load_set2_ground_truth_data('/content/drive/folder_location/Jio Internship Codes/data/EntityRelationship_ManualLabel_Set2.xlsx')

# Load predicted data
predicted_df_mistralv2_processed = load_set2_predicted_data(
    '../data/mistral_output_resp_dataset2_100.xlsx', file_type='excel'
    # '/content/drive/folder_location/Jio Internship Codes/data/mistral_output_resp_dataset2_100.xlsx', file_type='excel'
)
predicted_df_mistralv3_processed = load_set2_predicted_data(
    '../data/mistralv0.3_output_resp_dataset2_128.csv', file_type='csv'
    # '/content/drive/folder_location/Jio Internship Codes/data/mistralv0.3_output_resp_dataset2_128.csv', file_type='csv'
)

# Extract common pairs and relationships
common_pairs_df_mistralv2 = extract_set2_common_pairs_and_relationships(
    ground_truth_df_processed, predicted_df_mistralv2_processed
)
common_pairs_df_mistralv3 = extract_set2_common_pairs_and_relationships(
    ground_truth_df_processed, predicted_df_mistralv3_processed
)

# Save results
save_data_to_excel(common_pairs_df_mistralv2,
                   '../output/common_pairs_new_relationships.xlsx'
                  #  '/content/drive/folder_location/Jio Internship Codes/output/common_pairs_new_relationships.xlsx'
                   )
save_data_to_excel(common_pairs_df_mistralv3,
                   '../output/common_pairs_new_relationships_mistral_v3.xlsx'
                  #  '/content/drive/folder_location/Jio Internship Codes/output/common_pairs_new_relationships_mistral_v3.xlsx'
                   )









