# -*- coding: utf-8 -*-
"""CoNLL04_classification_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BF-gG2daEJAiCimk_c8CgeXtoAZNOUm
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import sys
# import os
# sys.path.append('/content/drive/folder_location/Jio Internship Codes')

# !pip install flair

# pip install datasets

import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np
from transformers import AutoTokenizer, AutoModel
from datasets import load_dataset
from sklearn.metrics.pairwise import cosine_similarity

from utils.helpers import load_model_and_tokenizer
from utils.data_processing import load_conll04_data, extract_relations_conll04, extract_relations_and_merge
from utils.embedding_utils import get_embeddings_conll04
from utils.model_utils import train_classifier, evaluate_model

# Load dataset and preprocess data
train_data, val_data, test_data = load_conll04_data()

mistral_files = {
    'train': '../data/mistralv0.3_output_resp_CoNLL04_train_prompt11 (1).csv',
    # 'train' : '/content/drive/folder_location/Jio Internship Codes/data/mistralv0.3_output_resp_CoNLL04_train_prompt11 (1).csv',
    'val': '../data/mistralv0.3_output_resp_CoNLL04_val_prompt11.csv',
    # 'val' : '/content/drive/folder_location/Jio Internship Codes/data/mistralv0.3_output_resp_CoNLL04_val_prompt11.csv',
    'test': '../data/mistralv0.3_output_resp_CoNLL04_test_prompt11 (1).csv'
    # 'test' : '/content/drive/folder_location/Jio Internship Codes/data/mistralv0.3_output_resp_CoNLL04_test_prompt11 (1).csv',
}
gpt4_files = {
    'train': '../data/gpt4_output_resp_CoNLL04_train_prompt11.csv',
    # 'train': '/content/drive/folder_location/Jio Internship Codes/data/gpt4_output_resp_CoNLL04_train_prompt11.csv',
    'val': '../data/gpt4_output_resp_CoNLL04_val_prompt11.csv',
    # 'val': '/content/drive/folder_location/Jio Internship Codes/data/gpt4_output_resp_CoNLL04_val_prompt11.csv',
    'test': '../data/gpt4_output_resp_CoNLL04_test_prompt11.csv'
    # 'test': '/content/drive/folder_location/Jio Internship Codes/data/gpt4_output_resp_CoNLL04_test_prompt11.csv'
}

# Extract relations
train_df_mistral, train_df_gpt4 = extract_relations_and_merge(train_data, mistral_files['train'], gpt4_files['train'])
val_df_mistral, val_df_gpt4 = extract_relations_and_merge(val_data, mistral_files['val'], gpt4_files['val'])
test_df_mistral, test_df_gpt4 = extract_relations_and_merge(test_data, mistral_files['test'], gpt4_files['test'])

# Load the embedding model
model_name = "sentence-transformers/all-mpnet-base-v2"
tokenizer, model = load_model_and_tokenizer(model_name)

# Embedding relations
train_df_mistral, val_df_mistral, test_df_mistral = get_embeddings_conll04(train_df_mistral, val_df_mistral, test_df_mistral, model, tokenizer)
train_df_gpt4, val_df_gpt4, test_df_gpt4 = get_embeddings_conll04(train_df_gpt4, val_df_gpt4, test_df_gpt4, model, tokenizer)

# Label encoding
label_encoder_mistral = LabelEncoder()
train_df_mistral['relation_label'] = label_encoder_mistral.fit_transform(train_df_mistral['ground_truth_relation'])
val_df_mistral['relation_label'] = label_encoder_mistral.transform(val_df_mistral['ground_truth_relation'])
test_df_mistral['relation_label'] = label_encoder_mistral.transform(test_df_mistral['ground_truth_relation'])

label_encoder_gpt4 = LabelEncoder()
train_df_gpt4['relation_label'] = label_encoder_gpt4.fit_transform(train_df_gpt4['ground_truth_relation'])
val_df_gpt4['relation_label'] = label_encoder_gpt4.transform(val_df_gpt4['ground_truth_relation'])
test_df_gpt4['relation_label'] = label_encoder_gpt4.transform(test_df_gpt4['ground_truth_relation'])

# Prepare training and validation data
X_train_mistral = np.vstack(train_df_mistral['predicted_relation_embedding'].values)
y_train_mistral = train_df_mistral['relation_label'].values
X_val_mistral = np.vstack(val_df_mistral['predicted_relation_embedding'].values)
y_val_mistral = val_df_mistral['relation_label'].values
X_test_mistral = np.vstack(test_df_mistral['predicted_relation_embedding'].values)
y_test_mistral = test_df_mistral['relation_label'].values

X_train_gpt4 = np.vstack(train_df_gpt4['predicted_relation_embedding'].values)
y_train_gpt4 = train_df_gpt4['relation_label'].values
X_val_gpt4 = np.vstack(val_df_gpt4['predicted_relation_embedding'].values)
y_val_gpt4 = val_df_gpt4['relation_label'].values
X_test_gpt4 = np.vstack(test_df_gpt4['predicted_relation_embedding'].values)
y_test_gpt4 = test_df_gpt4['relation_label'].values

# Train classifiers
clf_mistral = train_classifier(X_train_mistral, y_train_mistral)
clf_gpt4 = train_classifier(X_train_gpt4, y_train_gpt4)

# Evaluate classifiers
accuracy_mistral, f1_micro_mistral, f1_macro_mistral, class_report_mistral = evaluate_model(clf_mistral, X_val_mistral, y_val_mistral, label_encoder_mistral)
print(f"Mistralv3 Validation Accuracy: {accuracy_mistral}")
print(f"Mistralv3 Validation Micro F1-score: {f1_micro_mistral}")
print(f"Mistralv3 Validation Macro F1-score: {f1_macro_mistral}")
print(class_report_mistral)

accuracy_gpt4, f1_micro_gpt4, f1_macro_gpt4, class_report_gpt4 = evaluate_model(clf_gpt4, X_val_gpt4, y_val_gpt4, label_encoder_gpt4)
print(f"GPT4 Validation Accuracy: {accuracy_gpt4}")
print(f"GPT4 Validation Micro F1-score: {f1_micro_gpt4}")
print(f"GPT4 Validation Macro F1-score: {f1_macro_gpt4}")
print(class_report_gpt4)

# Test scores
accuracy_mistral_test, f1_micro_mistral_test, f1_macro_mistral_test, class_report_mistral_test = evaluate_model(clf_mistral, X_test_mistral, y_test_mistral, label_encoder_mistral)
print(f"Mistralv3 Test Accur acy: {accuracy_mistral_test}")
print(f"Mistralv3 Test Micro F1-score: {f1_micro_mistral_test}")
print(f"Mistralv3 Test Macro F1-score: {f1_macro_mistral_test}")
print(class_report_mistral_test)

accuracy_gpt4_test, f1_micro_gpt4_test, f1_macro_gpt4_test, class_report_gpt4_test = evaluate_model(clf_gpt4, X_test_gpt4, y_test_gpt4, label_encoder_gpt4)
print(f"GPT4 Test Accuracy: {accuracy_gpt4_test}")
print(f"GPT4 Test Micro F1-score: {f1_micro_gpt4_test}")
print(f"GPT4 Test Macro F1-score: {f1_macro_gpt4_test}")
print(class_report_gpt4_test)