# -*- coding: utf-8 -*-
"""gpt4_relations_clustering(iteration2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0J_noplWFS5qshWteFQEfd9M6d0yyXd
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import sys
# import os
# sys.path.append('/content/drive/folder_location/Jio Internship Codes')

# !pip install flair

# !pip install datasets

import pandas as pd
import json
from sklearn.metrics.pairwise import cosine_similarity
from flair.embeddings import TransformerDocumentEmbeddings
from flair.data import Sentence

from utils.helpers import load_model_and_tokenizer
from utils.embedding_utils import get_embedding
from utils.assign_clusters import assign_to_topk_clusters
from utils.data_processing import load_gpt4_data
from utils.evaluation_utils import evaluate_embedding_models

def clustering(model_name,
               output_filename,
               clusters_path='../data/Base_Clusters.xlsx',
              #  clusters_path='/content/drive/folder_location/Jio Internship Codes/data/Base_Clusters.xlsx',
               new_rels_path='../data/GPT_Relationships.xlsx'
              #  new_rels_path='/content/drive/folder_location/Jio Internship Codes/data/GPT_Relationships.xlsx'
               ):

    # Load Data
    clusters_df, new_rels_df = load_gpt4_data(clusters_path, new_rels_path)

    # Prepare Clusters
    clusters = {col: clusters_df[col].dropna().tolist() for col in clusters_df.columns}

    # Load Model
    if "transformers" or "Snowflake" in model_name:
        tokenizer, model = load_model_and_tokenizer(model_name)
        embedding_type = "transformers"
    elif "flair" in model_name:
        model = TransformerDocumentEmbeddings(model_name)
        embedding_type = "flair"
    else:
        raise ValueError(f"Unsupported model type for model_name: {model_name}")

    # Compute Embeddings for Clusters
    cluster_embeddings = {}
    for column in clusters_df.columns:
        cluster_rels = clusters_df[column].dropna().tolist()
        if embedding_type == "transformers":
            cluster_embeddings[column] = [get_embedding(word, model, tokenizer, use_flair=False) for word in cluster_rels]
        elif embedding_type == "flair":
            cluster_embeddings[column] = [get_embedding(model, tokenizer, use_flair=True) for word in cluster_rels]

    # Assign Relationships to Top 5 Clusters
    assignments = []

    for column in new_rels_df.columns:
        new_rels = new_rels_df[column].dropna().tolist()
        for rel in new_rels:
            if embedding_type == "transformers":
                word, top_clusters = assign_to_topk_clusters(rel, cluster_embeddings, model, tokenizer, top_k=5, similarity_metric='mean', use_flair=False)
            elif embedding_type == "flair":
                word, top_clusters = assign_to_topk_clusters(rel, cluster_embeddings, model, tokenizer, top_k=5, similarity_metric='mean', use_flair=True)

            original_cluster = column
            assignments.append({
                'relationship': word,
                'original_cluster': original_cluster,
                '1st_best_cluster': top_clusters[0],
                '2nd_best_cluster': top_clusters[1],
                '3rd_best_cluster': top_clusters[2],
                '4th_best_cluster': top_clusters[3],
                '5th_best_cluster': top_clusters[4]
            })
            clusters[top_clusters[0]].append(word + '**')

    # Create DataFrames for Results
    assignments_df = pd.DataFrame(assignments)
    updated_clusters_df = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in clusters.items()]))

    # Save Results
    with pd.ExcelWriter(f'../output/{output_filename}') as writer:
    # with pd.ExcelWriter(f'/content/drive/folder_location/Jio Internship Codes/output/{output_filename}') as writer:
        updated_clusters_df.to_excel(writer, sheet_name='Updated Clusters', index=False)
        assignments_df.to_excel(writer, sheet_name='Cluster Assignments', index=False)

    return assignments_df

if __name__ == "__main__":
    with open('../configs/models.json', 'r') as file:
    # with open('/content/drive/folder_location/Jio Internship Codes/configs/models.json', 'r') as file:
        models = json.load(file)

    for model in models:
        model_name = model["model_name"]
        output_filename = model["output_filename"]
        assignments_df = clustering(model_name, output_filename)
        evaluate_embedding_models(assignments_df, model_name)