# -*- coding: utf-8 -*-
"""set1_data_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEI6LLdL9d5mi8gHBlsxyguMMlqqh_ee
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import sys
# import os
# sys.path.append('/content/drive/folder_location/Jio Internship Codes')

# !pip install flair

import pandas as pd
from utils.embedding_utils import get_embedding, get_cluster_embeddings
from utils.assign_clusters import assign_to_cluster
from utils.helpers import load_model_and_tokenizer
from transformers import AutoTokenizer, AutoModel

def set1_clustering(model_name='sentence-transformers/paraphrase-MiniLM-L6-v2',
                    rels_path='../data/NewsEntityExtraction_Mistral_Phi3(model_comparison).csv',
                    # rels_path='/content/drive/folder_location/Jio Internship Codes/data/NewsEntityExtraction_Mistral_Phi3(model_comparison).csv',
                    clusters_path='../data/New Cluster Mappings.xlsx',
                    # clusters_path='/content/drive/folder_location/Jio Internship Codes/data/New Cluster Mappings.xlsx',
                    output_path='../output/new_cluster_results.xlsx'
                    # output_path='/content/drive/folder_location/Jio Internship Codes/output/new_cluster_results.xlsx'
                    ):
  rels_df = pd.read_csv(rels_path, encoding='latin1')
  clusters_df = pd.read_excel(clusters_path, header=0, sheet_name='Cluster Words2')

  tokenizer, model = load_model_and_tokenizer(model_name)

  news_summaries = rels_df['News Summary']
  ground_truths = rels_df['GT_relationship']
  predicted_mistral = rels_df['Mistral_relationship']
  predicted_phi3 = rels_df['Phi3_relationship']

  clusters, cluster_embeddings = get_cluster_embeddings(clusters_df, model, tokenizer)

  new_clusters = {cluster: words.copy() for cluster, words in clusters.items()}
  results = []
  for idx in range(len(news_summaries)):
      news_summary = news_summaries[idx]
      try:
          ground_truth = eval(ground_truths[idx])
      except:
          continue

      if 'nan' in ground_truth:
          continue

      pred_mistral = eval(predicted_mistral[idx]) if isinstance(predicted_mistral[idx], str) else predicted_mistral[idx]
      pred_phi3 = eval(predicted_phi3[idx]) if isinstance(predicted_phi3[idx], str) else predicted_phi3[idx]

      gt_clusters = [assign_to_cluster(gt, cluster_embeddings, model, tokenizer) for gt in ground_truth]
      pred_mistral_clusters = [assign_to_cluster(pm, cluster_embeddings, model, tokenizer) for pm in pred_mistral]
      pred_phi3_clusters = [assign_to_cluster(pp, cluster_embeddings, model, tokenizer) for pp in pred_phi3]

      for gt, gt_cluster in gt_clusters:
          for pm, pm_cluster in pred_mistral_clusters:
              results.append([news_summary, 'Mistral', gt, gt_cluster, pm, pm_cluster, gt_cluster == pm_cluster])
              new_clusters[pm_cluster].append(pm + '*')
          for pp, pp_cluster in pred_phi3_clusters:
              results.append([news_summary, 'Phi3', gt, gt_cluster, pp, pp_cluster, gt_cluster == pp_cluster])
              new_clusters[pp_cluster].append(pp + '*')
          if gt not in new_clusters[gt_cluster]:
              new_clusters[gt_cluster].append(gt + '#')

  results_df = pd.DataFrame(results, columns=['news_summary', 'model', 'ground_truth_relationship', 'ground_truth_cluster', 'predicted_relationship', 'predicted_cluster', 'same_cluster'])
  updated_clusters_df = pd.DataFrame.from_dict(new_clusters, orient='index').transpose()

  with pd.ExcelWriter(output_path) as writer:
      results_df.to_excel(writer, sheet_name='Cluster_Assignment_Results', index=False)
      updated_clusters_df.to_excel(writer, sheet_name='Updated_Clusters', index=False)

  return results_df

if __name__ == "__main__":
    results = set1_clustering()