# -*- coding: utf-8 -*-
"""set2_mean_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCRF0bCnFRWKkV6YbC0MZRDIAwd2-VRA
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import sys
# import os
# sys.path.append('/content/drive/folder_location/Jio Internship Codes')

# !pip install flair

import pandas as pd
from utils.helpers import load_model_and_tokenizer
from utils.embedding_utils import get_embedding, get_cluster_embeddings
from utils.assign_clusters import assign_to_topk_clusters
from utils.evaluation_utils import calculate_metrics
from sklearn.metrics.pairwise import cosine_similarity

def mean_based_clustering(model_name="sentence-transformers/all-mpnet-base-v2",
                          clusters_path='../data/top_5_clusters_mpnet.xlsx',
                          # clusters_path='/content/drive/folder_location/Jio Internship Codes/data/top_5_clusters_mpnet.xlsx',
                          new_rels_path='../data/common_pairs_new_relationships.xlsx',
                          # new_rels_path='/content/drive/folder_location/Jio Internship Codes/data/common_pairs_new_relationships.xlsx',
                          output_results_path='../output/mean_cluster_assignments_set2.xlsx',
                          # output_results_path='/content/drive/folder_location/Jio Internship Codes/output/mean_cluster_assignments_set2.xlsx',
                          output_clusters_path='../output/set2_updated_clusters_mean.xlsx',
                          # output_clusters_path='/content/drive/folder_location/Jio Internship Codes/output/set2_updated_clusters_mean.xlsx',
                          similarity_threshold=0.4):

    # Load data
    clusters_df = pd.read_excel(clusters_path, sheet_name='Updated Clusters')
    new_rels_df = pd.read_excel(new_rels_path)

    # Preprocess new relationships
    new_rels_df['relationship_gt'] = new_rels_df['relationship_gt'].str.replace('_', ' ')
    new_rels_df['relationship_pred'] = new_rels_df['relationship_pred'].str.replace('_', ' ')

    news_summaries = new_rels_df['news_summary']
    ground_truths = new_rels_df['relationship_gt']
    predicted_mistral = new_rels_df['relationship_pred']

    # Load model and tokenizer
    tokenizer, model = load_model_and_tokenizer(model_name)

    # Get cluster embeddings
    clusters, cluster_embeddings = get_cluster_embeddings(clusters_df, model, tokenizer)

    results = []
    new_clusters = {cluster: words.copy() for cluster, words in clusters.items()}

    # Process each relationship
    for idx in range(len(news_summaries)):
        news_summary = news_summaries[idx]
        gt = ground_truths[idx]
        pm = predicted_mistral[idx]

        # Assign clusters
        gt_cluster = assign_to_topk_clusters(gt, cluster_embeddings, model, tokenizer, top_k=1, similarity_metric='mean', use_flair=False)[1]
        # pred_mistral_cluster = assign_to_topk_clusters(pm, cluster_embeddings, model, tokenizer, top_k=5, similarity_metric='mean', use_flair=False)[1]
        gt_embedding = get_embedding(gt, model, tokenizer)
        pm_embedding = get_embedding(pm, model, tokenizer)
        similarity = cosine_similarity([gt_embedding], [pm_embedding])[0][0]
        if similarity > similarity_threshold:
            pred_mistral_cluster = [gt_cluster[0]]
            _, other_top_clusters = assign_to_topk_clusters(pm, cluster_embeddings, model, tokenizer, top_k=5, similarity_metric='mean', use_flair=False)
            pred_mistral_cluster.extend([cluster for cluster in other_top_clusters if cluster != gt_cluster[0]][:4])
            pred_relationship = pm
        else:
            pred_mistral_cluster = assign_to_topk_clusters(pm, cluster_embeddings, model, tokenizer, top_k=5, similarity_metric='mean', use_flair=False)[1]

        # Collect results
        results.append({
            'news_summary': news_summary,
            'Ground Truth': gt,
            'gt_relationship': gt_cluster[0],
            'Predicted': pm,
            '1st_pred_cluster': pred_mistral_cluster[0],
            '2nd_pred_cluster': pred_mistral_cluster[1],
            '3rd_pred_cluster': pred_mistral_cluster[2],
            '4th_pred_cluster': pred_mistral_cluster[3],
            '5th_pred_cluster': pred_mistral_cluster[4]
        })

        # Update clusters
        if gt not in new_clusters[gt_cluster[0]]:
            new_clusters[gt_cluster[0]].append(gt + '#')
        if pm not in new_clusters[pred_mistral_cluster[0]]:
            new_clusters[pred_mistral_cluster[0]].append(pm + '*')

    # Save results to Excel
    results_df = pd.DataFrame(results)
    results_df.to_excel(output_results_path, index=False)

    # Update and save clusters
    for col in clusters_df.columns:
        if col in new_clusters:
            clusters_df[col] = pd.Series(new_clusters[col])

    clusters_df.to_excel(output_clusters_path, index=False)

    return results_df

if __name__ == "__main__":
    results = mean_based_clustering()
    calculate_metrics(results, top_k=5, task_type='mean_median')







