# -*- coding: utf-8 -*-
"""set2_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFuvwNQNLZ8H0Clre73AL-y-W_yXnpKz
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import sys
# import os
# sys.path.append('/content/drive/folder_location/Jio Internship Codes')

# !pip install flair

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.ensemble import RandomForestClassifier
from utils.helpers import load_model_and_tokenizer
from utils.embedding_utils import get_embedding, get_cluster_embeddings
from utils.assign_clusters import assign_to_topk_clusters_classifier
from utils.model_utils import train_classifier
from utils.evaluation_utils import calculate_metrics

def classification_based_clustering(version,
                                    similarity_threshold=0.4,
                                    model_name='sentence-transformers/all-mpnet-base-v2',
                                    clusters_path='../data/top_5_clusters_mpnet.xlsx',
                                    # clusters_path='/content/drive/folder_location/Jio Internship Codes/data/top_5_clusters_mpnet.xlsx',
                                    mistral_v2_new_rels_path='../data/common_pairs_new_relationships.xlsx',
                                    # mistral_v2_new_rels_path='/content/drive/folder_location/Jio Internship Codes/data/common_pairs_new_relationships.xlsx',
                                    mistral_v3_new_rels_path='../data/common_pairs_new_relationships_mistral_v3.xlsx',
                                    # mistral_v3_new_rels_path='/content/drive/folder_location/Jio Internship Codes/data/common_pairs_new_relationships_mistral_v3.xlsx',
                                    mistral_v2_results_path='../output/rf_cluster_assignments_set2_0.4threshold.xlsx',
                                    # mistral_v2_output_results_path='/content/drive/folder_location/Jio Internship Codes/output/rf_cluster_assignments_set2_0.4threshold.xlsx',
                                    mistral_v3_results_path='../output/rf_assignments_set2_with_threshold_mistralv3.xlsx',
                                    # mistral_v3_output_results_path='/content/drive/folder_location/Jio Internship Codes/output/rf_assignments_set2_with_threshold_mistralv3.xlsx',
                                    mistral_v2_output_clusters_path='../output/rf_updated_clusters_set2_with_threshold.xlsx',
                                    # mistral_v2_output_clusters_path='/content/drive/folder_location/Jio Internship Codes/output/rf_updated_clusters_set2_with_threshold.xlsx',
                                    mistral_v3_output_clusters_path='../output/rf_clusters_set2_with_threshold_mistralv3.xlsx'
                                    # mistral_v3_output_clusters_path='/content/drive/folder_location/Jio Internship Codes/output/rf_clusters_set2_with_threshold_mistralv3.xlsx'
                                    ):

    clusters_df = pd.read_excel(clusters_path, sheet_name='Updated Clusters')
    if version == 'mistralv2':
        new_rels_df = pd.read_excel(mistral_v2_new_rels_path)
        results_file = mistral_v2_output_results_path
        updated_clusters_file = mistral_v2_output_clusters_path
    elif version == 'mistralv3':
        new_rels_df = pd.read_excel(mistral_v3_new_rels_path)
        results_file = mistral_v3_output_results_path
        updated_clusters_file = mistral_v3_output_clusters_path
    else:
        raise ValueError("Invalid version specified. Choose 'mistralv2' or 'mistralv3'.")

    new_rels_df['relationship_gt'] = new_rels_df['relationship_gt'].str.replace('_', ' ')
    new_rels_df['relationship_pred'] = new_rels_df['relationship_pred'].str.replace('_', ' ')

    news_summaries = new_rels_df['news_summary']
    ground_truths = new_rels_df['relationship_gt']
    predicted_mistral = new_rels_df['relationship_pred']

    tokenizer, model = load_model_and_tokenizer(model_name)

    clusters, cluster_embeddings = get_cluster_embeddings(clusters_df, model, tokenizer)

    all_embeddings = []
    all_labels = []
    for cluster, embeddings in cluster_embeddings.items():
        all_embeddings.extend(embeddings)
        all_labels.extend([cluster] * len(embeddings))

    all_embeddings = np.array(all_embeddings)

    rf_classifier = train_classifier(all_embeddings, all_labels)

    new_clusters = {cluster: words.copy() for cluster, words in clusters.items()}
    results = []

    for idx in range(len(news_summaries)):
        news_summary = news_summaries[idx]
        gt = ground_truths[idx]
        pm = predicted_mistral[idx]

        gt_relationship, gt_cluster = assign_to_topk_clusters_classifier(gt, model, tokenizer, rf_classifier, top_k=5)
        gt_embedding = get_embedding(gt, model, tokenizer)
        pm_embedding = get_embedding(pm, model, tokenizer)
        similarity = cosine_similarity([gt_embedding], [pm_embedding])[0][0]
        if similarity > similarity_threshold:
            pred_mistral_cluster = [gt_cluster[0]]
            _, other_top_clusters = assign_to_topk_clusters_classifier(pm, model, tokenizer, rf_classifier, top_k=5)
            pred_mistral_cluster.extend([cluster for cluster in other_top_clusters if cluster != gt_cluster[0]][:4])
            pred_relationship = pm
        else:
            pred_mistral_cluster = assign_to_topk_clusters_classifier(pm, model, tokenizer, rf_classifier, top_k=5)[1]
            pred_relationship = pm

        result = {
            'news_summary': news_summary,
            'Ground Truth': gt_relationship,
            'gt_relationship': gt_cluster[0],
            'Predicted': pred_relationship
        }

        for i in range(min(5, len(pred_mistral_cluster))):
            result[f'{i+1}st_pred_cluster'] = pred_mistral_cluster[i] if len(pred_mistral_cluster) > i else None

        results.append(result)

        if gt + '#' not in new_clusters[gt_cluster[0]]:
            new_clusters[gt_cluster[0]].append(gt + '#')
        if pm + '*' not in new_clusters[pred_mistral_cluster[0]]:
            new_clusters[pred_mistral_cluster[0]].append(pm + '*')

    results_df = pd.DataFrame(results)
    updated_clusters_df = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in new_clusters.items()]))
    results_df.to_excel(results_file, index=False)
    updated_clusters_df.to_excel(updated_clusters_file, index=False)

    return results_df

if __name__ == "__main__":
    results = classification_based_clustering(version='mistralv3')
    calculate_metrics(results, top_k=5, task_type='classification')



